### ISSUE TITLE
Consider django-nap as alternative to DRF

### ISSUE THREAD

**Issue by jpic** [delitamakanda/django-react#1]
Great project ! This is just a question, did you consider django-nap instead of DRF, if so, why have you choosen DRF ?
Keep up the great work ! I'm django dev + js enthusiast so this project helps me a lot :joy:

**Comment by jpic** [comment]
Another alternative is GraphQL, have you considered it ?
http://graphene-python.org/

**Comment by delitamakanda** [comment]
Merci de ta contribution 👍 . Je ne connaissais pas django-nap. C'est une alternative aussi intéressante que django-tastypie.
